language: python
python:
    - "3.6"
install:
    - pip install -r test-requirements.txt
script:
  - make test

after_success:
  - |
        pip install coverage==3.6 coveralls
        coverage combine
        coveralls
notifications:
  email:
    on_failure: change
    on_success: never
