sudo: required
language: python
services:
  - docker

script:
  - make test-in-docker

after_success:
  - |

        sudo docker create --name results-cont welder/lorax-composer
        sudo docker cp results-cont:/lorax/.coverage .coverage
        sudo docker rm results-cont

        pip install coveralls
        coveralls

notifications:
  email:
    on_failure: change
    on_success: never
